{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 -- Generated by Oracle SQL Developer Data Modeler 4.1.3.901\
--   at:        2016-09-11 13:32:53 AEST\
--   site:      Oracle Database 12c\
--   type:      Oracle Database 12c\
\
\
\
\
CREATE TABLE battery\
  (\
    id             INTEGER NOT NULL ,\
    machine_id     INTEGER ,\
    soc            NUMERIC ,\
    last_updated   TIMESTAMP ,\
    avaliable      NUMBER ,\
    date_purchased TIMESTAMP ,\
    date_removed   TIMESTAMP\
  ) ;\
ALTER TABLE battery ADD CONSTRAINT battery_PK PRIMARY KEY ( id ) ;\
\
\
CREATE TABLE battery_user\
  (\
    id        INTEGER NOT NULL ,\
    firstname VARCHAR ,\
    lastname  VARCHAR ,\
    credit    NUMERIC\
  ) ;\
ALTER TABLE battery_user ADD CONSTRAINT battery_user_PK PRIMARY KEY ( id ) ;\
\
\
CREATE TABLE machine\
  (\
    id            INTEGER NOT NULL ,\
    gps_location  NUMERIC ,\
    text_location VARCHAR ,\
    model_type    VARCHAR\
  ) ;\
ALTER TABLE machine ADD CONSTRAINT machine_PK PRIMARY KEY ( id ) ;\
\
\
CREATE TABLE rental_log\
  (\
    id              INTEGER NOT NULL ,\
    user_id         INTEGER ,\
    battery_id      INTEGER ,\
    machine_id      INTEGER ,\
    time_rented     TIMESTAMP ,\
    time_returned   TIMESTAMP ,\
    initial_charge  NUMERIC ,\
    final_charge    NUMERIC ,\
    battery_user_id INTEGER\
  ) ;\
ALTER TABLE rental_log ADD CONSTRAINT rental_log_PK PRIMARY KEY ( id ) ;\
\
\
ALTER TABLE battery ADD CONSTRAINT battery_machine_FK FOREIGN KEY ( machine_id ) REFERENCES machine ( id ) ;\
\
ALTER TABLE rental_log ADD CONSTRAINT rental_log_battery_FK FOREIGN KEY ( battery_id ) REFERENCES battery ( id ) ;\
\
ALTER TABLE rental_log ADD CONSTRAINT rental_log_battery_user_FK FOREIGN KEY ( battery_user_id ) REFERENCES battery_user ( id ) ;\
\
ALTER TABLE rental_log ADD CONSTRAINT rental_log_machine_FK FOREIGN KEY ( machine_id ) REFERENCES machine ( id ) ;\
\
\
-- Oracle SQL Developer Data Modeler Summary Report: \
-- \
-- CREATE TABLE                             4\
-- CREATE INDEX                             0\
-- ALTER TABLE                              8\
-- CREATE VIEW                              0\
-- ALTER VIEW                               0\
-- CREATE PACKAGE                           0\
-- CREATE PACKAGE BODY                      0\
-- CREATE PROCEDURE                         0\
-- CREATE FUNCTION                          0\
-- CREATE TRIGGER                           0\
-- ALTER TRIGGER                            0\
-- CREATE COLLECTION TYPE                   0\
-- CREATE STRUCTURED TYPE                   0\
-- CREATE STRUCTURED TYPE BODY              0\
-- CREATE CLUSTER                           0\
-- CREATE CONTEXT                           0\
-- CREATE DATABASE                          0\
-- CREATE DIMENSION                         0\
-- CREATE DIRECTORY                         0\
-- CREATE DISK GROUP                        0\
-- CREATE ROLE                              0\
-- CREATE ROLLBACK SEGMENT                  0\
-- CREATE SEQUENCE                          0\
-- CREATE MATERIALIZED VIEW                 0\
-- CREATE SYNONYM                           0\
-- CREATE TABLESPACE                        0\
-- CREATE USER                              0\
-- \
-- DROP TABLESPACE                          0\
-- DROP DATABASE                            0\
-- \
-- REDACTION POLICY                         0\
-- TSDP POLICY                              0\
-- \
-- ORDS DROP SCHEMA                         0\
-- ORDS ENABLE SCHEMA                       0\
-- ORDS ENABLE OBJECT                       0\
-- \
-- ERRORS                                   0\
-- WARNINGS                                 0\
}