ALTER TABLE public.passwordresettoken
  OWNER TO ovs;
ALTER TABLE public.privilege
  OWNER TO ovs;
ALTER TABLE public.role
  OWNER TO ovs;
ALTER TABLE public.roles_privileges
  OWNER TO ovs;
ALTER TABLE public.users
  OWNER TO ovs;
ALTER TABLE public.users_roles
  OWNER TO ovs;
ALTER TABLE public.verificationtoken
  OWNER TO ovs;
