-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-07-18 10:07:31 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c


CREATE TABLE passwordresettoken
  (
    id         INTEGER  ,
    expirydate TIMESTAMP ,
    token      VARCHAR ,
    users_id   INTEGER 
  ) ;
ALTER TABLE passwordresettoken ADD CONSTRAINT passwordresettoken_PK PRIMARY KEY ( id ) ;


CREATE TABLE privilege
  ( id INTEGER  , name VARCHAR
  ) ;
ALTER TABLE privilege ADD CONSTRAINT privilege_PK PRIMARY KEY ( id ) ;


CREATE TABLE role
  ( id INTEGER  , name VARCHAR
  ) ;
ALTER TABLE role ADD CONSTRAINT role_PK PRIMARY KEY ( id ) ;


CREATE TABLE roles_privileges
  (
    privilege_id INTEGER  ,
    role_id      INTEGER 
  ) ;


CREATE TABLE users
  (
    id                 INTEGER  ,
    email              VARCHAR ,
    enabled            BOOLEAN  ,
    firstname          VARCHAR ,
    lastname           VARCHAR ,
    password           VARCHAR ,
    tokenexpired       BOOLEAN,
	username		   VARCHAR
  ) ;

  ;
ALTER TABLE users ADD CONSTRAINT users_PK PRIMARY KEY ( id ) ;


CREATE TABLE users_roles
  (
    role_id  INTEGER  ,
    users_id INTEGER 
  ) ;


CREATE TABLE verificationtoken
  (
    id         INTEGER  ,
    expirydate TIMESTAMP ,
    token      VARCHAR ,
    users_id   INTEGER 
  ) ;
ALTER TABLE verificationtoken ADD CONSTRAINT verificationtoken_PK PRIMARY KEY ( id ) ;


ALTER TABLE passwordresettoken ADD CONSTRAINT passwordresettoken_users_FK FOREIGN KEY ( users_id ) REFERENCES users ( id ) ;

ALTER TABLE roles_privileges ADD CONSTRAINT roles_privileges_privilege_FK FOREIGN KEY ( privilege_id ) REFERENCES privilege ( id ) ;

ALTER TABLE roles_privileges ADD CONSTRAINT roles_privileges_role_FK FOREIGN KEY ( role_id ) REFERENCES role ( id ) ;

ALTER TABLE users ADD CONSTRAINT users_builder_FK FOREIGN KEY ( builder_builder_id ) REFERENCES builder ( builder_id ) ;

ALTER TABLE users_roles ADD CONSTRAINT users_roles_role_FK FOREIGN KEY ( role_id ) REFERENCES role ( id ) ;

ALTER TABLE users_roles ADD CONSTRAINT users_roles_users_FK FOREIGN KEY ( users_id ) REFERENCES users ( id ) ;

ALTER TABLE verificationtoken ADD CONSTRAINT verificationtoken_users_FK FOREIGN KEY ( users_id ) REFERENCES users ( id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            22
-- CREATE INDEX                             5
-- ALTER TABLE                             44
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  23
-- WARNINGS                                 0
